on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-build-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 2

      - name: Check changed files meet build linter requirements
        run: |
          CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD | xargs)
          ./automation/pull-request/lint-build-files.sh $CHANGED_FILES
          if [ $? -ne 0 ]; then
            echo "::warning::Build files in this PR did not pass optional checks. Please review for accuracy! See check-build-files step for details."
          fi
        continue-on-error: true