name: Dummy Action
on:
  # Allows you to run this workflow manually from the Actions tab
  # Use context values as : ${{ github.event.inputs.BRANCH }}
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  push: 
    branches: [dummy-branch]

jobs:
  dummy-action:
    name: Copy something from one branch to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Run some shell commands
        run: | 
          echo $(date -u -v -5d +%s)
