name: Dummy Action
on:
  # Allows you to run this workflow manually from the Actions tab
  # Use context values as : ${{ github.event.inputs.BRANCH }}
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  push: 
    branches: [dummy-branch]

jobs:
  dummy-action:
    name: Test shell commands
    runs-on: ubuntu-latest
    steps:
      - name: Make a bunch of random folders with date.txt files
        run: |
          mkdir folder1
          mkdir folder1/new
          mkdir folder1/old
          mkdir folder2
          mkdir folder2/super_old
          mkdir folder3
          mkdir folder3/unrelated
          echo $(date -u +%s) > folder1/date.txt
          echo $(date -u +%s) > folder1/new/date.txt
          echo $(date -u -d "5 days ago" +%s) > folder1/old/date.txt
          echo $(date -u -d "10 days ago" +%s) > folder2/date.txt
          echo $(date -u -d "10 days ago" +%s) > folder2/super_old/date.txt
          ls -R
          
      - name: Delete old folders
        run: |
          directories=($(find . -name date.txt -exec dirname {}))
          for directory in $directories; do
            date_in_file_utc=$(cat "$directory/date.txt")
            five_days_ago_utc=$(date -u -d "5 days ago" +%s)
            if ((date_in_file_utc < five_days_ago_utc)); then
              rm -rf $directory
            fi
          done
          ls -R

