name: Publish to GH Pages

on:
  workflow_call:
    inputs:
      artifactName:
        description: The artifact to publish to gh-pages. This should be the name of a build artifact from a previous step in the workflow, not a filepath.
        type: string
        required: true
      destinationPath:
        description: The path to the directory where the artifact should be downloaded. Please omit the gh-pages prefix from the path.
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: "gh-pages/${{ inputs.destinationPath }}"

      - name: Commit and push to GH Pages
        shell: bash
        run: |
          git pull
          git add -f . 
          git commit -m "Downloading build artifact ${{ inputs.artifactName }} to ${{ inputs.destinationPath }}"
          git push