name: Test Reusable GH Pages Actions

on:
  push:
    branch: [ unittest-publish-to-ghpages ]
  workflow_dispatch:

jobs:
  test-action:
    name: Copy something from one branch to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Make downloads directory
        run: |
          mkdir html_downloads
          cd html_downloads
          mkdir first_directory
          mkdir second_directory
          mkdir third_directory
          cd third_directory
          mkdir fourth_directory

      - name: Generate html files
        run: |
          cd html_downloads
          echo 'This is the first file' > first_directory/alpha.html
          echo 'This is also a first directory file'> first_directory/another.html
          echo 'This is the modified second file' > second_directory/beta.html
          echo 'And this is the last file' > third_directory/fourth_directory/omega.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html_downloads_artifact
          path: html_downloads

  publish:
    name: Publish artifacts to GH Pages
    needs: test-action
    uses: ./.github/workflows/Reusable-Publish-To-GH-Pages.yml
    with:
      artifactName: html_downloads_artifact
      destinationPath: tempDirectory/${{ github.run_id }}

  indexTopLevel:
    name: Generate Index File
    needs: publish
    uses: ./.github/workflows/Reusable-Generate-Index-Page.yml
    with:
      path: tempDirectory

  indexCompletely:
    name: Generate Complete Index Tree for Run
    needs: indexTopLevel
    uses: ./.github/workflows/Reusable-Generate-Complete-Index-Tree.yml
    with:
      path: tempDirectory/${{ github.run_id }}
