name: Validate Build Files

on:
  pull_request:
    branches: [ main ]

jobs:
  get-changed-build-files:
    runs-on: ubuntu-latest
    outputs:
      build-files: ${{ steps.collect-files.outputs.files }}
    steps:

      - name: Check out the repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 2

      - name: Collect changed files
        id: collect-files
        run: |
          ALL_CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
          INST_BUILD_FILES=$(echo "$ALL_CHANGED_FILES" | grep 'instrumentation/.*\.gradle$')
          FILES_AS_JSON_ARR=$(echo "$INST_BUILD_FILES" | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES_AS_JSON_ARR" >> $GITHUB_OUTPUT

  execute-validations:
    runs-on: ubuntu-latest
    needs: get-changed-build-files
    strategy:
      matrix:
        file: ${{ fromJSON(needs.get-changed-build-files.outputs.build-files) }}
    steps:
      - name: Run validation scripts
        env:
          file: ${{ matrix.file }}
        run: |
          set +e
          if ! ./automation/pull-request/check-verify.sh "$file"; then
            echo "::warning file=$file::(Optional) $file did not contain expected verifyInstrumentation stanza. Please review for accuracy." 
          fi
          if ! ./automation/pull-request/check-implementation-title.sh "$file"; then 
            echo "::warning file=$file::(Optional) $file did not contain expected implementation title. Please review for accuracy."
          fi
